[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://wubia.netlify.app"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Time in seconds to not submit the sitemap after successful submission
	ignorePeriod = 0

	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]

[[plugins]]
  package = "netlify-plugin-chromium"
    [plugins.inputs]
      packageManager = "npm"
      setChromePathInEnv = false
      failBuildOnError = false

[[plugins]]
package = "netlify-plugin-image-optim"